spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: jjunyong
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  kurly:
    api: https://api.kurly.com/search/v2/normal-search